2022 branding update
UQComputingSociety/signup pull request #47
Opened 2022-01-24 01:12 UTC by Thomas-Malcolm

It's not 2021 anymore!

Changed branding information to be 2022, update program data and documentation.

2022-01-24 01:15 UTC, JamesDearlove commented
Will need to be rebased onto new master, and requires Azure merged first.

2022-01-24 01:15 UTC, JamesDearlove requested changes
Blocking until we merge azure stuff

2022-01-25 00:20 UTC, JamesDearlove approved these changes
My name is James Dearlove, and I approve of this pull request

2022-01-25 00:25 UTC, TomCranitch approved these changes

2022-01-25 00:28 UTC, merged